# title of website
title: Sigs's Nav

# description of website
description: chasla's navigation site

# favicon of website
favicon: "https://github.com/chasla.png?size=40"

# your website url
url: https://chasla.github.io/nav/

# github profile url
github: "https://si.gs"

# footer message
footer: © 2021-2021 @Sigs

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: VIOX
          description: VIOX
          url: https://viox.com/
        - name: oyunfor
          description: 土区APPLE Giftcard购买
          url: https://www.oyunfor.com/apple-store/apple-store-itunes-gift-card
        - name: bestblogs
          description: 新闻汇集feed阅读
          url: https://www.bestblogs.dev/feeds?featured=y
        - name: 工具集合
          description: 实用工具集合
          url: https://tool.lu/
        - name: 工具集合
          description: 实用工具集合
          url: https://tool.lu/
        - name: hostinger
          description: hostinger后台
          url: https://hpanel.hostinger.com/
        - name: multcloud
          description: 网盘同步平台
          url: https://www.multcloud.com/
        - name: 火车票查询
          description: 火车票查询
          url: https://mobile.12306.cn/weixin/wxcore/init
        - name: 飞机票查询
          description: 飞机票查询
          url: https://www.fliggy.com/
    - name: AI
      sites:
        - name: perplexity
          description: perplexity（推荐）
          url: https://www.perplexity.ai/
        - name: Devv
          description: Devv
          url: https://devv.ai/
        - name: phind
          description: phind
          url: https://phind.com/
        - name: Chatgpt
          description: Chatgpt
          url: https://chatgpt.com/
    - name: 工具导航
      sites:
        - name: IT人必备
          description: IT人必备（推荐）
          url: https://666666.dev/
        - name: 帮小忙
          description: 腾讯帮小忙
          url: https://tool.browser.qq.com/
        - name: 出海工具箱
          description: 出海工具箱
          url: https://indiehackertools.net/
        - name: sinqi
          description: sinqi tools
          url: https://sinqi.tools/
    - name: 网络调试
      sites:
        - name: IPINFO
          description: IP查询
          url: https://ipinfo.io/
        - name: IPchecking
          description: IPChecking
          url: https://ipcheck.ing/
        - name: DNSdumpster
          description: DNS解析查询
          url: https://dnsdumpster.com/
        - name: fofa
          description: 网络空间搜索引擎
          url: https://en.fofa.info/
        - name: namebeta
          description: 各类域名后缀注册查询
          url: https://namebeta.com/
    - name: 下载资源
      sites:
        - name: BTnull
          description: 网盘资源
          url: https://www.btnull.org/user/login/
        - name: 盘友社区
          description: 阿里网盘资源
          url: https://ali.pan123456789.com/
    - name: SEO
      sites:
        - name: SEO手册
          description: SEO手册
          url: https://allinone.quickso.cn/
        - name: SEO新手指南
          description: SEO新手指南
          url: https://ahrefs.com/zh/seo
        - name: SEOBOX
          description: SEOBOX
          url: https://seo.box/
        - name: aitdk
          description: seochrome插件
          url: https://seo.box/
        - name: SEOjournal
          description: SEO资讯站
          url: https://www.searchenginejournal.com/
        - name: Semrush
          description: Semrush
          url: https://www.semrush.com/
        - name: Similarweb
          description: Similarweb
          url: https://www.similarweb.com/
        - name: ahrefs
          description: ahrefs
          url: https://www.ahrefs.com/
        - name: Seo工具
          description: Seo工具
          url: https://seo.chuhai.tools/
    - name: 工具
      sites:
        - name: 微信公众号排版
          description: 微信公众号排版
          url: https://doocs.github.io/md/
        - name: 12FT  
          description: 破收费阅读
          url: https://12ft.io/
        - name: SVGviewer 
          description: SVG编辑器
          url: https://svgviewer.dev/
        - name: picprose  
          description: 封面图片编辑
          url: https://www.picprose.net/en
        - name: cobalt
          description: 视频下载(推荐）
          url: https://cobalt.tools/
        - name: Savetube
          description: 油管视频下载
          url: https://save.tube/
        - name: v.hi.sy
          description: 油管视频下载
          url: https://v.hi.sy/
        - name: inpaintweb
          description: 图片去除多余人物
          url: https://inpaintweb.lxfater.com/
    - name: 电子邮箱
      sites:
        - name: Fastmail
          description: fastmail
          url: https://www.fastmail.com/
        - name: gmail地址生成器
          description: Gmail地址生成器
          url: https://gmail.inputekno.com/
        - name: Gmail临时邮箱
          description: Gmail临时邮箱
          url: https://smailpro.com/
        - name: tabular
          description: email邮件模版
          url: https://tabular.email/
        - name: HTML邮件
          description: HTML邮件
          url: https://beefree.io/
        - name: Email Once
          description: Email Once
          url: https://email-once.com/
        - name: Email.ml
          description: Email.Ml
          url: http://email.ml/
        - name: sendcloud
          description: 群发邮件
          url: https://www.sendcloud.net/home
        - name: Dmarcly
          description: Dmarcly Tools
          url: https://dmarcly.com/tools/
    - name: 其他
      sites:
        - name: 诗词学习
          description: 中国诗词学习网站
          url: https://aspoem.com/zh-Hans
        - name: earthworm
          description: 英语学习网
          url: https://earthworm.cuixueshe.com/
