# title of website
title: Sigs's Nav

# description of website
description: Sigs's navigation site

# favicon of website
favicon: "https://github.com/chasla.png?size=40"

# your website url
url: https://si.gs

# github profile url
sigs: "https://si.gs"

# footer message
footer: © 2024-2024 @Sigs

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: false
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: oyunfor
          description: 土区APPLE Giftcard购买
          url: https://www.oyunfor.com/apple-store/apple-store-itunes-gift-card
        - name: bestblogs
          description: 新闻汇集feed阅读
          url: https://www.bestblogs.dev/feeds?featured=y
        - name: hostinger
          description: hostinger后台
          url: https://hpanel.hostinger.com/
        - name: multcloud
          description: 网盘同步平台
          url: https://www.multcloud.com/
        - name: 火车票查询
          description: 火车票查询
          url: https://mobile.12306.cn/weixin/wxcore/init
        - name: 飞机票查询
          description: 飞机票查询
          url: https://www.fliggy.com/
        - name: teracloud
          description: 因我有45G永久容量
          url: https://seto.teracloud.jp/browser/
    - name: AI
      sites:
        - name: perplexity
          description: perplexity（推荐）
          url: https://www.perplexity.ai/
        - name: Devv
          description: Devv
          url: https://devv.ai/
        - name: phind
          description: phind
          url: https://phind.com/
        - name: Chatgpt
          description: Chatgpt
          url: https://chatgpt.com/
        - name: Coze
          description: coze
          url: https://coze.com/
        - name: claude
          description: claude
          url: https://claude.ai/
        - name: gemini
          description: 谷歌大模型
          url: https://gemini.google.com/
        - name: 微软copilot
          description: 微软copilot
          url: https://copilot.microsoft.com/
        - name: cohere
          description: cohere
          url: https://cohere.com/
        - name: groq
          description: groq
          url: https://groq.com/
        - name: 通义千问
          description: 阿里大模型
          url: https://tongyi.aliyun.com/qianwen/
        - name: 文心一言
          description: 百度大模型
          url: https://yiyan.baidu.com/agreement
        - name: 豆包
          description: 抖音大模型
          url: https://doubao.com
        - name: kimi
          description: kimi
          url: https://kimi.moonshot.cn/
        - name: Gpts hunter
          description: Gpts推荐
          url: https://gptshunter.com/
        - name: AI大模型入门
          description: AI大模型入门
          url: https://s3tlxskbq3.feishu.cn/docx/NyPqdCKraoXz9gxNVCfcIFdnnAc
        - name: Chatgpt指令大全
          description: Chatgpt指令大全
          url: https://www.explainthis.io/zh-hans/chatgpt
        - name: AI指令生成
          description: AI指令生成
          url: https://prompt-generator.llm2d.cc/
        - name: 各大模型比价
          description: LLM比价工具
          url: https://llmpricecheck.com/
        - name: 国产模型比价
          description: LLM比价工具
          url: https://aigcrank.cn/llmprice/
        - name: openl
          description: AI内容识别探测
          url: https://openl.io/ai-detector
        - name: ChatTTS
          description: AI语音生成（推荐）
          url: https://github.com/2noise/ChatTTS
    - name: 工具导航
      sites:
        - name: IT人必备
          description: IT人必备（推荐）
          url: https://666666.dev/
        - name: 帮小忙
          description: 腾讯帮小忙
          url: https://tool.browser.qq.com/
        - name: 出海工具箱
          description: 出海工具箱
          url: https://indiehackertools.net/
        - name: 出海工具箱
          description: 出海工具箱
          url: https://github.com/weijunext/indie-hacker-tools
        - name: sinqi
          description: sinqi tools
          url: https://sinqi.tools/
        - name: 工具集合
          description: 实用工具集合
          url: https://tool.lu/
    - name: 新闻信息
      sites:
        - name: tophub
          description: 今日热榜
          url: https://tophub.today/
        - name: 什么值得看
          description: 什么值得看
          url: https://smzdk.top/
        - name: readhub
          description: readhub
          url: https://readhub.cn/
        - name: 浑水阅读
          description: 浑水阅读
          url: https://www.hsmy.fun/
        - name: Hacker News
          description: Hacker News
          url: https://news.ycombinator.com
    - name: 网络调试
      sites:
        - name: IPINFO
          description: IP查询
          url: https://ipinfo.io/
        - name: IPchecking
          description: IPChecking
          url: https://ipcheck.ing/
        - name: DNSdumpster
          description: DNS解析查询
          url: https://dnsdumpster.com/
        - name: fofa
          description: 网络空间搜索引擎
          url: https://en.fofa.info/
        - name: namebeta
          description: 各类域名后缀注册查询
          url: https://namebeta.com/
        - name: WebRTC Leak
          description: WebRTC Leak
          url: https://browserleaks.com/webrtc
        - name: ipleak
          description: ipleak
          url: https://ipleak.net/
    - name: SEO
      sites:
        - name: SEO手册
          description: SEO手册
          url: https://allinone.quickso.cn/
        - name: SEO新手指南
          description: SEO新手指南
          url: https://ahrefs.com/zh/seo
        - name: SEOBOX
          description: SEOBOX
          url: https://seo.box/
        - name: aitdk
          description: seochrome插件
          url: https://seo.box/
        - name: SEOjournal
          description: SEO资讯站
          url: https://www.searchenginejournal.com/
        - name: Semrush
          description: Semrush
          url: https://www.semrush.com/
        - name: Similarweb
          description: Similarweb
          url: https://www.similarweb.com/
        - name: ahrefs
          description: ahrefs
          url: https://www.ahrefs.com/
        - name: Seo工具
          description: Seo工具
          url: https://seo.chuhai.tools/
    - name: 文字编辑工具
      sites:
        - name: 微信公众号排版
          description: 微信公众号排版
          url: https://doocs.github.io/md/
        - name: Word公文编辑模版
          description: Word公文编辑模版
          url: https://github.com/chasla/word-templates
        - name: JINA
          description: URL在线PDF解析文本
          url: https://r.jina.ai/
        - name: Geekcard
          description: 卡片文字分享工具
          url: https://geekcard.app/
        - name: 12FT  
          description: 破收费阅读
          url: https://12ft.io/
    - name: 图片编辑工具
      sites:
        - name: ideogram
          description: logo设计生成
          url: https://ideogram.ai/t/explore
        - name: removebg
          description: 背景消除
          url: https://www.remove.bg/
        - name: imagedraft
          description: 小红书twitter配图ai生成
          url: https://imagedraft.com/
        - name: SVGviewer 
          description: SVG编辑器
          url: https://svgviewer.dev/
        - name: picprose  
          description: 封面图片编辑
          url: https://www.picprose.net/en
        - name: spacexcode  
          description: 封面图生成器
          url: https://spacexcode.com/coverview/
        - name: inpaintweb
          description: ai抠图
          url: https://inpaintweb.lxfater.com/
        - name: removebg
          description: ai抠图
          url: https://removebg.one/
    - name: 视频编辑工具
      sites:
        - name: cobalt
          description: 视频下载(推荐）
          url: https://cobalt.tools/
        - name: Savetube
          description: 油管视频下载
          url: https://save.tube/
        - name: superparse
          description: 油管视频下载
          url: https://superparse.com/
        - name: v.hi.sy
          description: 油管视频下载
          url: https://v.hi.sy/
        - name: 无版权音乐
          description: 无版权音乐
          url: https://mixkit.co/
    - name: 站长工具
      sites:
        - name: awesome-cloudflare
          description: 赛博佛祖cloudflare
          url: https://github.com/zhuima/awesome-cloudflare
        - name: easyscraper爬虫
          description: 免费可视化爬虫
          url: https://easyscraper.com/
        - name: instantdata爬虫
          description: 免费可视化爬虫（推荐）+搭配chatgpt
          url: https://webrobots.io/instantdata/
    - name: MJJ
      sites:
        - name: nodeseek
          description: nodeseek
          url: https://www.nodeseek.com
        - name: hostloc
          description: hostloc
          url: https://www.hostloc.com
        - name: dalao
          description: 短域名论坛
          url: https://www.dalao.net
        - name: tld-list
          description: 最低价域名注册
          url: https://zh-hans.tld-list.com/
        - name: 哪煮米
          description: 最低价域名注册
          url: https://nazhumi.com/
        - name: spaceship
          description: 注册6数xyz
          url: https://spaceship.com/
        - name: racknerd
          description: vps
          url: https://www.racknerd.com
        - name: kurun
          description: vps
          url: https://www.kurun.com
    - name: 跨境外贸
      sites:
        - name: 跨境电商AI提示词
          description: 跨境电商AI提示词
          url: https://www.m123.com/ChatGPT
        - name: 各国节假日
          description: 各国节假日
          url: https://www.timeanddate.com/holidays/
        - name: 船舶定位
          description: 船舶定位
          url: https://www.shipxy.com/
        - name: 中行外汇牌价
          description: 中行外汇牌价
          url: https://www.boc.cn/sourcedb/whpj/
    - name: 下载资源
      sites:
        - name: BTnull
          description: 网盘资源
          url: https://www.btnull.org/user/login/
        - name: 盘友社区
          description: 阿里网盘资源
          url: https://ali.pan123456789.com/
    - name: 电子邮箱
      sites:
        - name: Fastmail
          description: fastmail
          url: https://www.fastmail.com/
        - name: gmail地址生成器
          description: Gmail地址生成器
          url: https://gmail.inputekno.com/
        - name: Gmail临时邮箱
          description: Gmail临时邮箱
          url: https://smailpro.com/
        - name: tabular
          description: email邮件模版
          url: https://tabular.email/
        - name: HTML邮件
          description: HTML邮件
          url: https://beefree.io/
        - name: Email Once
          description: Email Once
          url: https://email-once.com/
        - name: Email.ml
          description: Email.Ml
          url: http://email.ml/
        - name: sendcloud
          description: 群发邮件
          url: https://www.sendcloud.net/home
        - name: Dmarcly
          description: Dmarcly Tools
          url: https://dmarcly.com/tools/
    - name: podcast
      sites:
        - name: 信息差
          description: 独立开发者出海周刊
          url: https://gapis.money/
    - name: 其他
      sites:
        - name: 诗词学习
          description: 中国诗词学习网站
          url: https://aspoem.com/zh-Hans
        - name: earthworm
          description: 英语学习网
          url: https://earthworm.cuixueshe.com/
        - name: 微软AI口语
          description: 微软AI口语练习
          url: https://coach.microsoft.com/
    - name: 开源软件
      sites:
        - name: QuickRecorder
          description: 开源录屏软件
          url: https://github.com/lihaoyun6/QuickRecorder
        - name: edgetunnel
          description: 懂的都懂
          url: https://github.com/cmliu/edgetunnel
        - name: 订阅汇集
          description: 各种订阅汇集管理
          url: https://github.com/cmliu/CF-Workers-SUB
